(begin
  (display (length '(1 2 3)))
  (display (make-string 3 (integer->char 97)))
  (display (char? (integer->char 65)))
  (display (char<? (integer->char 97) (integer->char 99)))
  (display (char>? (integer->char 97) (integer->char 99)))
  (display (char<=? (integer->char 97) (integer->char 97)))
  (display (string<? "abc" "b"))
  (display (string=? "foo" "foo"))
  (display (substring "hello" 1 4))
  (display (string-copy "hi"))
  (let ((s (make-string 2 (integer->char 120))))
    (string-fill! s (integer->char 121))
    (display s))
  (display (string->list "ab"))
  (display (list->string (list (integer->char 99) (integer->char 100))))
)
