(begin
  (display (+ 1 2))
  (display (* 2 3))
  (display (- 5 2))
  (display (/ 9 3))
  (display (modulo 10 3))
  (display (< 1 2))
  (display (> 2 1))
  (display (= 3 3))
  (display (>= 3 2))
  (display (<= 2 2))
  (display (cons 1 2))
  (display (car (cons 1 2)))
  (display (cdr (cons 1 2)))
  (display (list 1 2 3))
  (display (eqv? 'a 'a))
  (display (boolean? #t))
  (display (symbol? 'x))
  (display (procedure? car))
  (display (pair? (cons 1 2)))
  (display (number? 5))
  (display (let ((x 1)) (set! x 3) x))
  (display (let ((p (cons 1 2))) (set-car! p 5) (set-cdr! p 6) p))
  (display (null? '()))
  (display (apply + '(1 2 3)))
  (display (string? "hi"))
  (display (symbol->string 'foo))
  (display (string->symbol "bar"))
  (display (string-append "ab" "cd" "ef"))
  (display (number->string 42))
)
